- platform: rest
  name: "Vera House Mode"
  resource: "http://[Vera_IP_address]:3480/data_request?id=variableget&Variable=Mode"
  method: "GET"
  scan_interval: 5
  value_template: >-
    {% set mapper =  {
      '1' : 'Home',
      '2' : 'Away',
      '3' : 'Night',
      '4' : 'Vacation' } %}
    {{ mapper[value] }}
